<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bdt extends Model
{
    protected $table = 'bdt_rt_51';

    protected $primaryKey = 'IDBDT';

    public $timestamps = false;

    protected $fillable = [
        'RUTA6',
        'NoPesertaPBDT',
        'NoPBDTKemsos',
        'Vector1',
        'Vector2',
        'Vector3',
        'Vector4',
        'KDGabungan4',
        'KDPROP',
        'KDKAB',
        'KDKEC',
        'KDDESA',
        'Alamat',
        'AdaPKH',
        'AdaPBDT',
        'AdaKKS2016',
        'AdaKKS2017',
        'AdaPBI',
        'AdaDapodik',
        'AdaBPNT',
        'NoPesertaPKH',
        'NoPesertaKKS2016',
        'NoPesertaPBI',
        'PesertaKIP',
        'NoKartuDebit',
        'Nama_SLS',
        'Nama_KRT',
        'Jumlah_ART',
        'Jumlah_Keluarga',
        'sta_bangunan',
        'sta_lahan',
        'luas_lantai',
        'lantai',
        'dinding',
        'kondisi_dinding',
        'atap',
        'kondisi_atap',
        'jumlah_kamar',
        'sumber_airminum',
        'nomor_meter_air',
        'cara_peroleh_airminum',
        'sumber_penerangan',
        'daya',
        'nomor_pln',
        'bb_masak',
        'nomor_gas',
        'fasbab',
        'kloset',
        'buang_tinja',
        'ada_tabung_gas',
        'ada_lemari_es',
        'ada_ac',
        'ada_pemanas',
        'ada_telepon',
        'ada_tv',
        'ada_emas',
        'ada_laptop',
        'ada_sepeda',
        'ada_motor',
        'ada_mobil',
        'ada_perahu',
        'ada_motor_tempel',
        'ada_perahu_motor',
        'ada_kapal',
        'aset_tak_bergerak',
        'luas_atb',
        'rumah_lain',
        'jumlah_sapi',
        'jumlah_kerbau',
        'jumlah_kuda',
        'jumlah_babi',
        'jumlah_kambing',
        'sta_art_usaha',
        'sta_kks',
        'sta_kip',
        'sta_kis',
        'sta_bpjs_mandiri',
        'sta_jamsostek',
        'sta_asuransi',
        'sta_pkh',
        'sta_rastra',
        'sta_kur',
        'sta_keberadaan_RT',
        'percentile',
        'id_pengurus',
        'Nama_Pengurus',
        'NIK_Pengurus',
        'Alamat_Pengurus',
        'Nama_Gadis_Ibu_Kandung_Pengurus',
        'JnsKel_Pengurus',
        'TglLahir_Pengurus',
        'HubKel_Pengurus',
        'InitData',
        'LastUpdateData',
        'kodewilayah',
        'IDver',
        'RID_RumahTangga',
        'typedta',
        'no_kks',
        'sumber_data',
        'uploaded_by',
        'kode_sls',
        'NOKK',
        'id_hh',
        'nourut_rt',
        'NoPBDTKemsos_2017',
        'KDPROP_2017',
        'KDKAB_2017',
        'KDKEC_2017',
        'KDDESA_2017',
        'adadivektor',
        'KDPROP_OLD',
        'KDKAB_OLD',
        'KDKEC_OLD',
        'KDDESA_OLD',
        'id_periode',
        'tgl_pindah',
        'oleh_pindah',
        'KET_BDTMEI18',
        'status'
    ];
    public function Bdt_art()
    {
        return $this->hasMany('Bdt_art');
    }
}